# Generated by Django 4.1.2 on 2022-10-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('overview', models.CharField(blank=True, max_length=254, null=True)),
                ('has_variants', models.BooleanField(blank=True, default=False, null=True)),
                ('variant_one', models.CharField(blank=True, max_length=254, null=True)),
                ('variant_one_stock_quantity', models.IntegerField(blank=True, null=True)),
                ('variant_two', models.CharField(blank=True, max_length=254, null=True)),
                ('variant_two_stock_quantity', models.IntegerField(blank=True, null=True)),
                ('variant_three', models.CharField(blank=True, max_length=254, null=True)),
                ('variant_three_stock_quantity', models.IntegerField(blank=True, null=True)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
