# Generated by Django 4.1.2 on 2022-10-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overview',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
