# Generated by Django 3.2 on 2022-09-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='old_price',
        ),
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
