# Generated by Django 3.2 on 2022-09-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220907_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_one',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_three',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_two',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
